# Generated by Django 5.2.4 on 2025-07-30 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('id_fabricante', models.CharField(blank=True, max_length=50, null=True)),
                ('detalle', models.CharField(max_length=255)),
                ('iva', models.CharField(blank=True, max_length=10, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('garantia', models.CharField(blank=True, max_length=50, null=True)),
                ('moneda', models.CharField(default='USD', max_length=10)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_utilidad', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('imagen', models.URLField(blank=True, max_length=500, null=True)),
                ('detalle_usuario', models.TextField(blank=True, null=True)),
                ('ean', models.CharField(blank=True, max_length=50, null=True)),
                ('upc', models.CharField(blank=True, max_length=50, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('alto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ancho', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('largo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('impuesto_interno', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('galeria', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
